### ISSUE TITLE
Question: Max Keys option set to 1000?

### ISSUE THREAD

**Issue by b-d-b** [arokor/barn#3]
I was wondering what the decision behind Max Keys option being set to 1000 is?  I'm unfamiliar with LocalStorage or this project and was wondering:

1) What happens if you exceed max keys for a barn?
2) Can I choose to increase max keys option programmatically?

Thanks, and this project is pretty awesome.

**Comment by arokor** [comment]
Hi Mike,

glad to hear that you like barn :) MaxKeys is purely technical and doesn't
affect how many items you can store in barn.

1) when maxKeys is reached barn condenses the stored changes to one key
containing a snapshot of the data stored up to that point. This is done in
order to save space and in a way that ensures data consistency even in if
the browser crashes during this operation.
2) No, but there is no need since this is an implementation detail and
doesn't affect how many keys you can store. Localstorage is normally
limited to 5 MB/domain so if you go on pumping data into barn you will at
some point reach a hard limit until then you can store as many keys as you
please.

Best regards
Aron





On Thu, Feb 4, 2016 at 7:00 PM, Mike K <notifications@github.com> wrote:

> I was wondering what the decision behind Max Keys option being set to 1000
> is? I'm unfamiliar with LocalStorage or this project and was wondering:
>
> 1) What happens if you exceed max keys for a barn?
> 2) Can I choose to increase max keys option programmatically?
>
> Thanks, and this project is pretty awesome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arokor/barn/issues/3>.
>



-- 

Med vänliga hälsningar

Aron

**Comment by b-d-b** [comment]
Thanks for the quick response, glad that that's purely an under the hood thing.  I was a little concerned but that definitely helps.
